version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=Proyecto
      - N8N_BASIC_AUTH_PASSWORD=Proyecto1234
    volumes:
      - ./n8n_data:/home/node/.n8n
      - "/c/Users/JULIO TORRES/Desktop/Proyecto/Documentos_utb:/files"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage